server:
  error:
    include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./hexletBlog"

  jpa:
    show-sql: true

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE
    # org.springframework.security: TRACE
    # io.hexlet.typoreporter: DEBUG
