---
logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  # mvc:
  #   log-request-details: true
  #   log-resolved-exception: true
  # codec:
  #   log-request-details: true
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0
